In [1]:
from pathlib import Path

import pandas as pd
import numpy as np

import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.data.load_data import load_raw_data

In [2]:
df = load_raw_data()

df.head()

======================================================================
CUSTOMER CHURN DATASET - INGESTION REPORT
======================================================================
Dataset path       : C:\Users\moham\Desktop\SLA\projects\Customer_churn_prediction\data\raw\Telco-Customer-Churn.csv
Number of rows     : 7,043
Number of columns  : 21

Duplicate customer IDs:
0

Target distribution:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Missing values:
Series([], dtype: int64)

Data types:
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object
======================================================================

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [12]:
print("Shape:", df.shape)

print("Columns:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i:02d}. {column}")

print("\nData types:")
display(df.dtypes)

Shape: (7043, 21)
Columns:
01. customerID
02. gender
03. SeniorCitizen
04. Partner
05. Dependents
06. tenure
07. PhoneService
08. MultipleLines
09. InternetService
10. OnlineSecurity
11. OnlineBackup
12. DeviceProtection
13. TechSupport
14. StreamingTV
15. StreamingMovies
16. Contract
17. PaperlessBilling
18. PaymentMethod
19. MonthlyCharges
20. TotalCharges
21. Churn

Data types:

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [4]:
print("TotalCharges dtype:")
print(df["TotalCharges"].dtype)

print("\nBlank values:")
print((df["TotalCharges"].astype(str).str.strip() == "").sum())

print("\nWhitespace-only values:")
print(df["TotalCharges"].astype(str).str.isspace().sum())

TotalCharges dtype:
str

Blank values:
11

Whitespace-only values:
11

In [7]:
blank_total_charges = df[
    df["TotalCharges"].astype(str).str.strip() == ""
]

display(blank_total_charges)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [8]:
display(
    blank_total_charges[
        ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
    ]
)

      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

In [9]:
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    print(f"\n{'=' * 60}")
    print(column)
    print(f"{'=' * 60}")
    print(df[column].value_counts(dropna=False))

============================================================
customerID
============================================================
customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

============================================================
gender
============================================================
gender
Male      3555
Female    3488
Name: count, dtype: int64

============================================================
Partner
============================================================
Partner
No     3641
Yes    3402
Name: count, dtype: int64

============================================================
Dependents
============================================================
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

============================================================
PhoneService
============================================================
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

============================================================
MultipleLines
============================================================
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

============================================================
InternetService
============================================================
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

============================================================
OnlineSecurity
============================================================
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

============================================================
OnlineBackup
============================================================
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

============================================================
DeviceProtection
============================================================
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

============================================================
TechSupport
============================================================
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

============================================================
StreamingTV
============================================================
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

============================================================
StreamingMovies
============================================================
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

============================================================
Contract
============================================================
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

============================================================
PaperlessBilling
============================================================
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

============================================================
PaymentMethod
============================================================
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

============================================================
TotalCharges
============================================================
TotalCharges
20.2      11
          11
19.75      9
19.9       8
20.05      8
          ..
1990.5     1
7362.9     1
346.45     1
306.6      1
6844.5     1
Name: count, Length: 6531, dtype: int64

============================================================
Churn
============================================================
Churn
No     5174
Yes    1869
Name: count, dtype: int64

C:\Users\moham\AppData\Local\Temp\ipykernel_23764\2007105201.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

In [10]:
print("Target distribution:")
print(df["Churn"].value_counts())

print("\nTarget percentage:")
print(
    (df["Churn"].value_counts(normalize=True) * 100)
    .round(2)
)

Target distribution:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Target percentage:
Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64